### ISSUE TITLE
VM creation failed

### ISSUE THREAD

**Issue by BalajiLoganathan** [mspnp/azure-data-factory-sqldw-elt-pipeline#2]
azbb -s <subscription_id> -g <resource_group_name> -l <region> -p onprem.parameters.json --deploy

getting this error. 

 error: error executing az
  message: 
  status: null
  arguments: vm list-skus --resource-type virtualMachines --zone false --subscription xxx

**Comment by LEONIDAS-BI** [comment]
Im getting exactly the same error when creating the VM by running the following command:

azbb -s <subscription_id> -g <resource_group_name> -l <region> -p onprem.parameters.json --deploy

**Comment by v-fearam** [comment]
Hi
I have detected error deploying the VM (#1), but I'm not able to see  "error executing az".
Please, try to install the latest Azure cli version (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
I will close this issue, but feel free to open again and provide more information if you consider.
Anyway, we will continue working on #1 to get the vm deployed
